server:
  port: 8081
  servlet:
    session:
      timeout: 24H
spring:
  profiles:
    active: @profileActive@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoint:
    shutdown:
      enabled: true # 开启端点
    health:
      show-details: always # 是否展示健康检查详情
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有端点

mybatis-plus:
  type-aliases-package: com.java668.oxadmin.modules.**.entity,com.java668.oxadmin.**.entity

logging:
  file-location: ./logs

# 代码生成
gen:
  # 作者
  author: jerry.chen
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.java668.oxadmin.modules.system
  # 自动去除表前缀，默认是false
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: syst_
