spring:
  datasource:
    url: jdbc:p6spy:mysql://${java668.mysql.host}/ox-admin?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${java668.mysql.username}
    password: ${java668.mysql.password}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: oxadmin
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# knife4j 接口文档
knife4j:
  enable: true
  openapi:
    title: OX-ADMIN
    description: 一个轻量级开源后端管理框架
    email: java668_real@163.com
    concat: 青牛
    url: https://github.com/java668/ox-admin
    version: v4.0
    license: Apache 2.0
    license-url: https://github.com/java668/ox-admin
    terms-of-service-url: https://github.com/java668/ox-admin
    group:
      system:
        group-name: 系统管理
        api-rule: package
        api-rule-resources:
          - com.java668.oxadmin.modules.system.controller
      generator:
        group-name: 代码生成
        api-rule: package
        api-rule-resources:
          - com.java668.oxadmin.modules.generator.controller
# 系统配置
oxadmin:
  system:
    isDemoSite: true



